### PR TITLE
typo breath -> breadth

### PR DESCRIPTION
**Pull request by AlexicaWright**
Thank you for your contribution to the Graph Data Science project.

Before submitting this PR, please make sure:
- [ ] You signed the [Neo4j CLA](https://neo4j.com/developer/cla/#sign-cla) (Contributor License Agreement) so that we are allowed to ship your code in our library
- [ ] Your contribution is covered by tests

### CODE REVIEW

**Review by vnickolov — APPROVED** [review]
Good catch, thank you very much 🙇

**Comment by FlorentinD** [comment]
@Mats-SX shouldnt this be cherry picked instead of merging into the mirror?

**Comment by vnickolov** [comment]
> @Mats-SX shouldnt this be cherry picked instead of merging into the mirror?

it was cherry-picked already

**Comment by Mats-SX** [comment]
@FlorentinD yeah this was my mistake

**Pull request merged**
