### PR TITLE
correction to the description of cypher projection data configuration

### PR DESCRIPTION
**Pull request by idan22moral**
Thank you for your contribution to the Graph Data Science project.

Before submitting this PR, please make sure:
- [x] You signed the [Neo4j CLA](https://neo4j.com/developer/cla/#sign-cla) (Contributor License Agreement) so that we are allowed to ship your code in our library
- [x] Your contribution is covered by tests

### CODE REVIEW

**Review by Mats-SX — APPROVED** [review]
Hello @idan22moral and thank you for this contribution. I am happy to approve and merge your changes. I confirm that this is a documentation bug.

I see your CLA email, but unfortunately it seems that you forgot to attach the CLA document to the email. Please, could you resend the email with the correct CLA attached to it? Then I will be happy to merge this PR.

**Comment by idan22moral** [comment]
@Mats-SX done

**Comment by Mats-SX** [comment]
Thank you, I can confirm your CLA signature.

**Comment by FlorentinD** [comment]
Sorry for letting this tiny PR sit for this long.
Thanks for finding this error in our documentation.

I cherry-picked your commit and you will see it tomorrow in this repo and also published for the 2.6 and preview versions of our documentation

**Pull request closed without merging**
