### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by frank-zsy**
The compatibility table not format right.

So adjust multi row height to make sure the table rendered right for GDS 1.7.x and 1.8.x.

Thank you for your contribution to the Graph Data Science project.

Before submitting this PR, please make sure:
- [x] You signed the Neo4j CLA (Contributor License Agreement) so that we are allowed to ship your code in our library. Not source code contribution, I assume no need to sign CLA since it is not source code.
- [x] Your contribution is covered by tests. Document update, no need to test.

### CODE REVIEW

**Comment by FlorentinD** [comment]
Hello @frank-zsy,
thank you for finding the formatting issue with our compatibility table and contributing a fix!

The CLA affects the whole repository, so we still have to ask you to sign it before we can accept your contribution (https://neo4j.com/developer/cla/#sign-cla).

**Comment by frank-zsy** [comment]
Understood, I have sent the mail and please check if it is OK~

**Comment by FlorentinD** [comment]
I could merge your PR in acee5d7213c3104a8c855a4578c4584c6f9e68cc :tada:

**Comment by frank-zsy** [comment]
@FlorentinD I am just curious about why this PR is not merged but you just fetched the commit and pushed back to master? Is there something to do with your CI procedure or other concerns?

**Comment by FlorentinD** [comment]
@frank-zsy Yes, it has something with our CI. Basically, every day we sync the commits of our private repository to this public repository here.

As this sync job is only from private to public, we cannot directly merge PRs here.

**Comment by frank-zsy** [comment]
Understood, thank you~

**Pull request closed without merging**
