### PR TITLE
Replace the term view in the document with a materialized view

### PR DESCRIPTION
**Pull request by nameof**
Replace the term view in the document with a materialized view，fix issue #122

### CODE REVIEW

**Comment by Mats-SX** [comment]
Hello @nameof and thanks for this contribution. In order to be able merge your change we need you to sign our contributor's agreement. Instructions for doing it can be found in our [contributor guidelines](https://github.com/neo4j/graph-data-science/blob/master/CONTRIBUTING.md). Your change is very simple, so all we really need is a CLA signature, [which is done per these instructions](https://neo4j.com/developer/cla/) (sending an email with your agreement). Once we have received it I will be happy to merge this.

**Review by Mats-SX — APPROVED** [review]
I agree, our graph projections are materialized views.

**Comment by nameof** [comment]
> Hello @nameof and thanks for this contribution. In order to be able merge your change we need you to sign our contributor's agreement. Instructions for doing it can be found in our [contributor guidelines](https://github.com/neo4j/graph-data-science/blob/master/CONTRIBUTING.md). Your change is very simple, so all we really need is a CLA signature, [which is done per these instructions](https://neo4j.com/developer/cla/) (sending an email with your agreement). Once we have received it I will be happy to merge this.

@Mats-SX I signed the CLA on the day I created the PR and sent it to cla@neotechnology.com. To avoid sending failure, I resent it again. Please check it out, thank you

**Comment by Mats-SX** [comment]
@nameof That is unfortunately not the correct email address. The domain is `neo4j.com`. Please can you send it again to that address?

**Comment by nameof** [comment]
> @nameof That is unfortunately not the correct email address. The domain is `neo4j.com`. Please can you send it again to that address?

@Mats-SX Oh, sorry, I have resent, please check, thank you

**Comment by Mats-SX** [comment]
I'm sorry, you actually did send it to the right address the first time; the domain is indeed `neotechnology.com`. Apologies for the confusion.

However, the email has not seemed to arrived. From what email address did you send the email?

**Comment by nameof** [comment]
> I'm sorry, you actually did send it to the right address the first time; the domain is indeed `neotechnology.com`. Apologies for the confusion.
> 
> However, the email has not seemed to arrived. From what email address did you send the email?

@Mats-SX I sent the mail from the address constexpr@foxmail.com. I just sent it again using chengpanexpr@gmail.com. Could you please check it again, thank you.

**Comment by Mats-SX** [comment]
@nameof Your signature has been received! Thanks a lot. I will cherry-pick your change to the internal repository, and then it will show up here tomorrow.

**Comment by Mats-SX** [comment]
@nameof Actually I triggered the repo sync so I can confirm that this is now merged. Thank you for your contribution!

https://github.com/neo4j/graph-data-science/commit/8be9f537182a15123067bc7ec29b7a4c44f2d0b7

**Pull request closed without merging**
